apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casdoor.fullname" . }}-config
data:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  app.conf: |-
{{ .Files.Get "config/app.conf" | indent 4}}
  init_data.json: |
{{ .Files.Get "config/init_data.json" | indent 4}}