apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casdoor.fullname" . }}-config
data:
  app.conf: |-
    appname = casdoor
    httpport = {{ .Values.service.port }}
    runmode = dev
    SessionOn = true
    copyrequestbody = true
    driverName = postgres
    dataSourceName = "user=postgres password={{ .Values.postgresql.auth.postgresPassword }} host={{ include "casdoor.fullname" . }}-postgresql port={{ .Values.postgresql.service.ports.postgresql }} sslmode=disable dbname={{ .Values.postgresql.auth.database }}"
    dbName = 
    tableNamePrefix =
    showSql = false
    redisEndpoint =
    defaultStorageProvider =
    isCloudIntranet = false
    authState = "casdoor"
    socks5Proxy = "127.0.0.1:10808"
    verificationCodeTimeout = 10
    initScore = 2000
    logPostOnly = true
    origin = "http://casdoor:8000"
    staticBaseUrl = "https://cdn.casbin.org"
    enableGzip = true
    initDataFile = "/init_data.json"

  init_data.json: |
{{ .Files.Get "config/init_data.json" | indent 4}}