helmDefaults:
  createNamespace: true
  timeout: 1200
repositories:
- name: sentry
  url: https://sentry-kubernetes.github.io/charts
- name: codecentric
  url: https://codecentric.github.io/helm-charts
releases:
- namespace: sentry
  name: casdoor
  chart: ./charts/casdoor
- namespace: sentry
  name: mailhog
  chart: codecentric/mailhog
  version: 5.2.3
- namespace: sentry
  name: sentry
  chart: sentry/sentry
  version: 21.0.0
  values:
  - values.yaml
- namespace: sentry
  name: burrow
  chart: ./charts/burrow
  version: 0.1.0
