images:
  sentry:
    repository: rophy/sentry
    tag: 23.6.1-20240128-r1
user:
  email: admin@sentry.local
  password: aaaa
sentry:
  singleOrganization: false
  web:
    env:
    - name: OIDC_CLIENT_ID
      value: 81a39e63a2eff8ca76a1
    - name: OIDC_CLIENT_SECRET
      value: 16f4967467fc2dfae42c7b86112f4e0db98df14c
    - name: OIDC_SCOPE
      value: openid profile email
    - name: OIDC_AUTHORIZATION_ENDPOINT
      value: http://casdoor:8000/login/oauth/authorize
    - name: OIDC_TOKEN_ENDPOINT
      value: http://casdoor:8000/api/login/oauth/access_token
    - name: OIDC_USERINFO_ENDPOINT
      value: http://casdoor:8000/api/userinfo
    - name: OIDC_ISSUER
      value: casdoor
system:
  url: http://sentry-nginx
postgresql:
  auth:
    postgresPassword: aaaa
clickhouse:
  clickhouse:
    persistentVolumeClaim:
      dataPersistentVolume:
        storage: "1Gi"
hooks:
  activeDeadlineSeconds: 600
config:
  configYml:
    mail.backend: smtp
    mail.host: mailhog.sentry.svc.cluster.local
    mail.port: 1025
    mail.from: admin@sentry.local
    mail.list-namespace: sentry.local

  sentryConfPy: |
    # Extra sentry.conf.py

    import os
    OIDC_CLIENT_ID = os.getenv('OIDC_CLIENT_ID')
    OIDC_CLIENT_SECRET = os.getenv('OIDC_CLIENT_SECRET')
    OIDC_SCOPE = os.getenv('OIDC_SCOPE')
    OIDC_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_AUTHORIZATION_ENDPOINT')
    OIDC_TOKEN_ENDPOINT = os.getenv('OIDC_TOKEN_ENDPOINT')
    OIDC_USERINFO_ENDPOINT = os.getenv('OIDC_USERINFO_ENDPOINT')
    OIDC_ISSUER = os.getenv('OIDC_ISSUER')
