user:
  email: admin@sentry.local
  password: aaaa
sentry:
  singleOrganization: false
postgresql:
  auth:
    postgresPassword: aaaa
clickhouse:
  clickhouse:
    persistentVolumeClaim:
      dataPersistentVolume:
        storage: "1Gi"
hooks:
  activeDeadlineSeconds: 600
