images:
  sentry:
    repository: rophy/sentry
    tag: 23.6.1-20240121-r1
user:
  email: admin@sentry.local
  password: aaaa
sentry:
  singleOrganization: false
  web:
    env:
    - name: OIDC_CLIENT_ID
      value: Iv1.b385556f38557fbc
    - name: OIDC_CLIENT_SECRET
      value: xxx # generate new one
    - name: OIDC_SCOPE
      value: openid email
    - name: OIDC_AUTHORIZATION_ENDPOINT
      value: https://github.com/login/oauth/authorize
    - name: OIDC_TOKEN_ENDPOINT
      value: https://github.com/login/oauth/access_token
    - name: OIDC_USERINFO_ENDPOINT
      value: https://github.com/api/userinfo
    - name: OIDC_ISSUER
      value: github-oauth
system:
  url: http://sentry-nginx
postgresql:
  auth:
    postgresPassword: aaaa
clickhouse:
  clickhouse:
    persistentVolumeClaim:
      dataPersistentVolume:
        storage: "1Gi"
hooks:
  activeDeadlineSeconds: 600
config:
  sentryConfPy: |
    # Extra sentry.conf.py

    import os
    OIDC_CLIENT_ID = os.getenv('OIDC_CLIENT_ID')
    OIDC_CLIENT_SECRET = os.getenv('OIDC_CLIENT_SECRET')
    OIDC_SCOPE = os.getenv('OIDC_SCOPE')
    OIDC_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_AUTHORIZATION_ENDPOINT')
    OIDC_TOKEN_ENDPOINT = os.getenv('OIDC_TOKEN_ENDPOINT')
    OIDC_USERINFO_ENDPOINT = os.getenv('OIDC_USERINFO_ENDPOINT')
    OIDC_ISSUER = os.getenv('OIDC_ISSUER')
