apiVersion: v2
name: casdoor
description: casdoor chart by rophy
type: application
version: 0.1.0
appVersion: "v1.509.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.3.1
